# Generated by Django 3.2.4 on 2022-08-03 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_parent_catalog_ref_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='ref_id',
            new_name='parent',
        ),
    ]
