# Generated by Django 3.2.4 on 2022-08-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_binary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='lft',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='rght',
            field=models.IntegerField(),
        ),
    ]
