# Generated by Django 3.2.4 on 2022-08-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_auto_20220804_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdetail',
            name='photo',
            field=models.ImageField(blank=True, default='images/face.jpg', upload_to='user_photos/'),
        ),
    ]
