# Generated by Django 3.2.4 on 2022-08-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_customerdetail_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetail',
            name='status',
            field=models.CharField(choices=[('Blacklist', 'Blacklist'), ('Suspend', 'Suspend'), ('Active', 'Active'), ('InActive', 'InActive')], default='Active', max_length=10),
        ),
    ]
