# Generated by Django 3.2.4 on 2022-08-08 18:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_customerdetail_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlogin',
            name='is_now_login',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerlogin',
            name='login_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 8, 8)),
        ),
        migrations.AddField(
            model_name='customerlogin',
            name='today_login_attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customerlogin',
            name='wrong_login_attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerlogin',
            name='login_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 8, 8, 23, 53, 20, 757389)),
        ),
    ]
