# Generated by Django 3.2.4 on 2022-08-11 18:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('customer', '0017_alter_customerlogin_login_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsInfo',
            fields=[
                ('acc_id', models.AutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('branch_code', models.IntegerField(blank=True, null=True)),
                ('acc_number', models.IntegerField(blank=True, null=True)),
                ('acc_title', models.CharField(blank=True, max_length=100)),
                ('acc_type', models.CharField(blank=True, max_length=100)),
                ('acc_status', models.CharField(blank=True, max_length=100)),
                ('pin', models.IntegerField(blank=True, null=True)),
                ('acc_activation_date', models.DateTimeField(blank=True)),
                ('city', models.ForeignKey(default=86, on_delete=django.db.models.deletion.CASCADE, to='main.cities')),
                ('country', models.ForeignKey(default=167, on_delete=django.db.models.deletion.CASCADE, to='main.countries')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.states')),
            ],
        ),
        migrations.AlterField(
            model_name='customerlogin',
            name='login_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 8, 11)),
        ),
        migrations.AlterField(
            model_name='customerlogin',
            name='login_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 8, 11, 23, 53, 16, 693505)),
        ),
        migrations.DeleteModel(
            name='Catalog',
        ),
    ]
