# Generated by Django 3.2.4 on 2022-08-11 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_auto_20220811_2353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountsinfo',
            old_name='pin',
            new_name='CVV',
        ),
        migrations.RenameField(
            model_name='accountsinfo',
            old_name='acc_activation_date',
            new_name='card_expiry_date',
        ),
        migrations.RemoveField(
            model_name='accountsinfo',
            name='city',
        ),
        migrations.RemoveField(
            model_name='accountsinfo',
            name='country',
        ),
        migrations.RemoveField(
            model_name='accountsinfo',
            name='state',
        ),
        migrations.AddField(
            model_name='accountsinfo',
            name='acc_holder_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='accountsinfo',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerlogin',
            name='login_date',
            field=models.DateField(blank=True, default=datetime.date(2022, 8, 12)),
        ),
        migrations.AlterField(
            model_name='customerlogin',
            name='login_time',
            field=models.TimeField(blank=True, default=datetime.datetime(2022, 8, 12, 0, 12, 42, 477187)),
        ),
    ]
