# Generated by Django 3.2.4 on 2022-08-01 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=50, null=True)),
                ('country_code', models.CharField(max_length=2, null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_code', models.CharField(max_length=4, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.countries')),
            ],
            options={
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_code', models.CharField(max_length=4, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.countries')),
                ('state', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.states')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
